name: myapp
description: "A new Flutter project."
publish_to: "none"
version: 1.4.0+6

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2
  file_picker: ^11.0.2
  mime: ^2.0.0
  lrc_parser: ^0.0.1
  audiotags: ^1.4.5
  google_fonts: ^8.0.2
  just_audio: ^0.10.5
  rxdart: ^0.28.0
  just_audio_media_kit: ^2.1.0

  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  collection: ^1.19.1
  permission_handler: ^12.0.1
  on_audio_query_forked: ^2.9.1
  flutter_animate: ^4.5.2
  flex_color_scheme: ^8.4.0
  flutter_speed_dial: ^7.0.0
  scrollable_positioned_list: ^0.3.8
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - lib/assets/
    - lib/assets/images/
    - assets/background/

  fonts:
    - family: NiShiKiFont
      fonts:
        - asset: lib/assets/fonts/nishiki-teki.ttf
